window.PoesiaData = {
  bins: [
    { id: "siciliana", label: "Scuola siciliana" },
    { id: "stilnovo", label: "Dolce stil novo" },
    { id: "comico", label: "Comico-realista" },
  ],
  casi: [
    {
      id: "c1",
      text: "Inventa il sonetto alla corte di Federico II",
      bin: "siciliana",
      hint: "Scuola siciliana (Giacomo da Lentini)",
    },
    {
      id: "c2",
      text: "Donna-angelo, linguaggio dolce e raffinato",
      bin: "stilnovo",
      hint: "Dolce stil novo",
    },
    {
      id: "c3",
      text: "«Tre cose… la donna, la taverna e ’l dado»",
      bin: "comico",
      hint: "Comico-realista (Cecco Angiolieri)",
    },
    {
      id: "c4",
      text: "Stile aspro e artificioso; poeti di corte/cancelleria",
      bin: "siciliana",
      hint: "Scuola siciliana",
    },
    {
      id: "c5",
      text: "Nobiltà d’animo, non solo di famiglia",
      bin: "stilnovo",
      hint: "Dolce stil novo",
    },
    {
      id: "c6",
      text: "Parodia dello stilnovo; linguaggio basso e cittadino",
      bin: "comico",
      hint: "Comico-realista",
    },
    {
      id: "c7",
      text: "Guido Guinizzelli considerato fondatore",
      bin: "stilnovo",
      hint: "Dolce stil novo",
    },
    {
      id: "c8",
      text: "Primo grande esempio di poesia in volgare in Sicilia",
      bin: "siciliana",
      hint: "Scuola siciliana",
    },
    {
      id: "c9",
      text: "Cecco prende in giro Dante e Beatrice",
      bin: "comico",
      hint: "Comico-realista",
    },
  ],
  percorso: [
    {
      pin: "1",
      x: 48,
      y: 78,
      luogo: "Palermo · volgare",
      tipo: "quiz",
      domanda: "Perché le origini della poesia italiana sono importanti?",
      opzioni: [
        { t: "Sono le prime esperienze letterarie in volgare (non più solo in latino)", ok: true },
        { t: "Perché si scrivevano solo in francese", ok: false },
        { t: "Perché nasce la prosa scientifica moderna", ok: false },
      ],
      spiegazione: "Il volgare illustre è l’antenato dell’italiano che parliamo.",
    },
    {
      pin: "2",
      x: 42,
      y: 72,
      luogo: "Corte di Federico II",
      tipo: "quiz",
      domanda: "Chi inventa il sonetto nella scuola siciliana?",
      opzioni: [
        { t: "Giacomo (Jacopo) da Lentini", ok: true },
        { t: "Cecco Angiolieri", ok: false },
        { t: "Petrarca", ok: false },
      ],
      spiegazione: "Il sonetto è il lascito più importante della scuola siciliana.",
    },
    {
      pin: "3",
      x: 38,
      y: 48,
      luogo: "Toscana · stilnovo",
      tipo: "quiz",
      domanda: "Cosa significa «dolce» nel Dolce stil novo?",
      opzioni: [
        { t: "Parla d’amore con linguaggio gentile e raffinato", ok: true },
        { t: "Usa solo dialetto siciliano", ok: false },
        { t: "È una poesia comica da taverna", ok: false },
      ],
      spiegazione: "Dolce = tema amoroso + stile alto e limpido.",
    },
    {
      pin: "4",
      x: 44,
      y: 42,
      luogo: "Donna-angelo",
      tipo: "quiz",
      domanda: "Nel stilnovo, la donna amata è spesso…",
      opzioni: [
        { t: "Vista come figura sublime, quasi angelica, tramite verso Dio", ok: true },
        { t: "Solo un pretesto per parlare di politica", ok: false },
        { t: "Sempre una prostituta da taverna", ok: false },
      ],
      spiegazione: "La donna-angelo è il centro dello stilnovo; Cecco farà l’opposto.",
    },
    {
      pin: "5",
      x: 52,
      y: 38,
      luogo: "Firenze · Dante",
      tipo: "quiz",
      domanda: "In «Tanto gentile e tanto onesta pare», quando Beatrice saluta…",
      opzioni: [
        { t: "Le lingue tremano e tacciono; gli occhi non osano guardare", ok: true },
        { t: "Tutti iniziano a ballare in piazza", ok: false },
        { t: "Dante le chiede subito di sposarlo", ok: false },
      ],
      spiegazione: "La gentilezza di Beatrice impone silenzio e rispetto.",
    },
    {
      pin: "6",
      x: 58,
      y: 34,
      luogo: "Taverna di Cecco",
      tipo: "quiz",
      domanda: "La poesia comico-realista di Cecco Angiolieri…",
      opzioni: [
        { t: "Parodia lo stilnovo e racconta la vita cittadina con linguaggio basso", ok: true },
        { t: "Imita solo il latino di Cicerone", ok: false },
        { t: "Inventa il sonetto a Palermo", ok: false },
      ],
      spiegazione: "Cecco è l’«opposto» ironico di Dante: realismo e invettiva.",
    },
  ],
};
