(function () {
  window.BAROCCO = {
    pins: [
      { id: "tesauro", left: "10.05%", top: "19.16%", label: "Tesauro · Torino" },
      { id: "chiabrera", left: "16.52%", top: "25.57%", label: "Chiabrera · Savona" },
      { id: "tassoni", left: "36.38%", top: "22.71%", label: "Tassoni · Modena" },
      { id: "galileo", left: "32.12%", top: "30.48%", label: "Galileo · Pisa" },
      { id: "napoli", left: "63.56%", top: "54.61%", label: "Marino e Basile · Napoli" },
    ],
    autori: [
      {
        id: "marino",
        pin: "napoli",
        nome: "Giambattista Marino",
        citta: "Napoli",
        anni: "1569–1625",
        opera: "Adone",
        cosa: "Il poeta più famoso del Barocco italiano. Vuole stupire. Frase da ricordare: «È del poeta il fin la meraviglia».",
        ritratto: "img/ritratto-marino.jpg",
        alt: "Ritratto di Giambattista Marino",
      },
      {
        id: "basile",
        pin: "napoli",
        nome: "Giambattista Basile",
        citta: "Napoli",
        anni: "1566–1632",
        opera: "Lo cunto de li cunti",
        cosa: "Scrive fiabe in napoletano. Anche Cenerentola arriva da qui, con il nome Gatta Cenerentola.",
        ritratto: "img/ritratto-basile.jpg",
        alt: "Ritratto di Giambattista Basile",
      },
      {
        id: "tassoni",
        pin: "tassoni",
        nome: "Alessandro Tassoni",
        citta: "Modena",
        anni: "1565–1635",
        opera: "La secchia rapita",
        cosa: "Un poema buffo. Modena e Bologna litigano per un secchio di legno. Si ride, ma è letteratura del Seicento.",
        ritratto: "img/ritratto-tassoni.jpg",
        alt: "Ritratto di Alessandro Tassoni",
      },
      {
        id: "chiabrera",
        pin: "chiabrera",
        nome: "Gabriello Chiabrera",
        citta: "Savona",
        anni: "1552–1638",
        opera: "Odi",
        cosa: "Cerca un ritmo più pulito. Meno gonfiore, più musica nel verso.",
        ritratto: "img/ritratto-chiabrera.jpg",
        alt: "Ritratto di Gabriello Chiabrera",
      },
      {
        id: "tesauro",
        pin: "tesauro",
        nome: "Emanuele Tesauro",
        citta: "Torino",
        anni: "1592–1675",
        opera: "Il cannocchiale aristotelico",
        cosa: "Spiega le metafore. Dice: la metafora è come un cannocchiale, fa vedere lontano.",
        ritratto: "img/ritratto-tesauro.jpg",
        alt: "Ritratto di Emanuele Tesauro",
      },
      {
        id: "galileo",
        pin: "galileo",
        nome: "Galileo Galilei",
        citta: "Pisa",
        anni: "1564–1642",
        opera: "Il Saggiatore",
        cosa: "Non è un poeta barocco. Scrive per spiegare, con parole chiare. Stesso secolo, altro modo.",
        ritratto: "img/ritratto-galileo.jpg",
        alt: "Ritratto di Galileo Galilei",
      },
    ],
  };
})();
