/* Dati didattici: Manzoni e I Promessi Sposi (da slide Canva del Prof.). */
window.ManzoniData = {
  personaggi: [
    {
      id: "renzo",
      nome: "Renzo Tramaglino",
      ruolo: "Protagonista",
      campo: "umili",
      x: 28,
      y: 58,
      sintesi: "Operaio tessile umile. Credente, ma a volte si allontana dalla volontà di Dio e paga le conseguenze.",
      punti: [
        "Persona comune: non è un eroe aristocratico",
        "Se pecca (rabbia, vendetta) le cose peggiorano",
        "Se segue Dio, la storia piega a suo favore",
      ],
    },
    {
      id: "lucia",
      nome: "Lucia Mondella",
      ruolo: "Protagonista",
      campo: "umili",
      x: 42,
      y: 48,
      sintesi: "Sarta di Lecco. Fede fortissima: modello di credente che non cede neppure nelle prove più dure.",
      punti: [
        "Rappresenta la fede costante",
        "Rapita per volontà di Don Rodrigo / Innominato",
        "Il voto e la liberazione passano dalla Provvidenza",
      ],
    },
    {
      id: "abbondio",
      nome: "Don Abbondio",
      ruolo: "Parroco timoroso",
      campo: "chiesa",
      x: 18,
      y: 36,
      sintesi: "Doveva sposare Renzo e Lucia. Non lo fa per paura dei Bravi. Federigo Borromeo lo rimprovera aspramente.",
      punti: [
        "Simbolo della paura che blocca il bene",
        "Non è «cattivo», è debole",
        "Contrapposto a Fra Cristoforo e a Federigo",
      ],
    },
    {
      id: "cristoforo",
      nome: "Fra Cristoforo",
      ruolo: "Frate buono",
      campo: "buoni",
      x: 55,
      y: 28,
      sintesi: "Prete di periferia che si sacrifica. Cerca fino all’ultimo di unire Renzo e Lucia; cura gli ammalati di peste fino alla morte.",
      punti: [
        "Coraggio morale contro i potenti",
        "Modello opposto a Don Abbondio",
        "Muore curando gli appestati",
      ],
    },
    {
      id: "federigo",
      nome: "Federigo Borromeo",
      ruolo: "Vescovo di Milano",
      campo: "buoni",
      x: 68,
      y: 38,
      sintesi: "Autorità ecclesiastica positiva: rimprovera Don Abbondio e rappresenta la Chiesa che serve, non che si nasconde.",
      punti: [
        "Contrappeso alla paura di Don Abbondio",
        "Figura storica reale nel romanzo",
        "Esempio di potere usato per il bene",
      ],
    },
    {
      id: "rodrigo",
      nome: "Don Rodrigo",
      ruolo: "Nobile prepotente",
      campo: "cattivi",
      x: 72,
      y: 62,
      sintesi: "Vuole Lucia. Usa i Bravi per impedire il matrimonio. La peste lo colpisce e muore: bilancia della Provvidenza.",
      punti: [
        "Potere abusato contro gli umili",
        "I Bravi sono i suoi scagnozzi",
        "Muore di peste: giustizia divina",
      ],
    },
    {
      id: "innominato",
      nome: "L’Innominato",
      ruolo: "Bandito convertito",
      campo: "cattivi",
      x: 82,
      y: 48,
      sintesi: "Rapisce Lucia per una scommessa e per aiutare Don Rodrigo. In una notte terribile Dio lo converte: libera Lucia.",
      punti: [
        "Dal male al bene: conversione",
        "Prova che anche il peggiore può cambiare",
        "Motore: la Provvidenza, non solo la volontà umana",
      ],
    },
    {
      id: "dio",
      nome: "Dio / Provvidenza",
      ruolo: "Motore del romanzo",
      campo: "provvidenza",
      x: 50,
      y: 14,
      sintesi: "Decide ogni cosa. Gli altri personaggi sono pedine. Converte l’Innominato, punisce Don Rodrigo, permette il matrimonio.",
      punti: [
        "Non servono solo principi e papi: Dio guida",
        "La peste punisce o salva secondo il comportamento",
        "Letteratura cristiana e «utile»",
      ],
    },
  ],

  eventi: [
    { id: "e1", testo: "I Bravi minacciano Don Abbondio: il matrimonio non si fa" },
    { id: "e2", testo: "Renzo e Lucia fuggono; le strade si separano" },
    { id: "e3", testo: "L’Innominato rapisce Lucia" },
    { id: "e4", testo: "Conversione dell’Innominato: Lucia è libera" },
    { id: "e5", testo: "La peste colpisce Milano e i personaggi" },
    { id: "e6", testo: "Don Rodrigo muore; Renzo e Lucia possono sposarsi" },
  ],

  abbinamenti: [
    { id: "a1", testo: "«Risciacquare i panni in Arno»", risposta: "lingua", spiegazione: "Manzoni riscrive i Promessi in fiorentino vivo, nobile e utile." },
    { id: "a2", testo: "Manoscritto ritrovato in soffitta", risposta: "espediente", spiegazione: "Espediente narrativo per eludere la censura austriaca." },
    { id: "a3", testo: "Ambientazione 1628–1630 in Lombardia", risposta: "storico", spiegazione: "Romanzo storico: persone comuni + ambientazione reale." },
    { id: "a4", testo: "Conversione notturna che libera Lucia", risposta: "provvidenza", spiegazione: "È Dio che converte l’Innominato, non solo un ripensamento umano." },
    { id: "a5", testo: "Rottura delle tre unità aristoteliche", risposta: "unita", spiegazione: "Tempo lungo, luoghi molti, trama articolata: Manzoni inaugura il romanzo moderno." },
  ],

  etichetteAbbinamento: {
    lingua: "Questione della lingua",
    espediente: "Espediente narrativo",
    storico: "Romanzo storico",
    provvidenza: "Provvidenza",
    unita: "Unità aristoteliche",
  },

  /* Coppie per il memory didattico (faccia A ↔ faccia B). */
  memory: [
    { id: "m1", a: "Renzo", b: "Uomo comune: se si allontana da Dio, le cose peggiorano" },
    { id: "m2", a: "Lucia", b: "Fede costante: modello di credente" },
    { id: "m3", a: "Don Abbondio", b: "Paura: non celebra il matrimonio" },
    { id: "m4", a: "L’Innominato", b: "Si converte e libera Lucia" },
    { id: "m5", a: "Don Rodrigo", b: "Muore di peste: bilancia della Provvidenza" },
    { id: "m6", a: "Risciacquare i panni in Arno", b: "Lingua: riscrivere in fiorentino" },
    { id: "m7", a: "Manoscritto in soffitta", b: "Espediente contro la censura austriaca" },
    { id: "m8", a: "Unità aristoteliche", b: "Manzoni le rompe: tempo lungo, tanti luoghi" },
  ],

  quiz: [
    {
      q: "Perché Manzoni sceglie il fiorentino?",
      choices: ["Perché è vivo, nobile e utile all’Italia unita", "Perché era obbligatorio per legge", "Perché odiava il milanese", "Per imitare i dialetti del Nord"],
      correct: 0,
      tema: "lingua",
    },
    {
      q: "Cosa significa «risciacquare i panni in Arno»?",
      choices: ["Lavare i vestiti a Firenze per moda", "Rivedere la lingua del romanzo sul modello fiorentino", "Trasferirsi a Firenze", "Copiare Dante parola per parola"],
      correct: 1,
      tema: "lingua",
    },
    {
      q: "Le tre opere principali di Manzoni (Cinque Maggio, Marzo 1821, Promessi Sposi) sono soprattutto…",
      choices: ["Di amore cortese", "Politiche", "Di pura evasione", "Di scienza"],
      correct: 1,
      tema: "opere",
    },
    {
      q: "Il Cinque Maggio parla soprattutto di…",
      choices: ["La peste di Milano", "Napoleone e la sua conversione", "I Bravi di Don Rodrigo", "I dialetti italiani"],
      correct: 1,
      tema: "opere",
    },
    {
      q: "Marzo 1821 è un elogio di…",
      choices: ["Gli austriaci", "I rivoluzionari dei moti che vogliono unire l’Italia", "Don Abbondio", "Luigi XIV"],
      correct: 1,
      tema: "opere",
    },
    {
      q: "Perché Manzoni ambienta i Promessi nel Seicento?",
      choices: ["Perché non conosceva l’Ottocento", "Per un espediente: eludere la censura austriaca", "Per copiare Walter Scott parola per parola", "Perché la peste era obbligatoria nei romanzi"],
      correct: 1,
      tema: "romanzo",
    },
    {
      q: "Chi sono i protagonisti «nuovi» del romanzo storico manzoniano?",
      choices: ["Solo re e papi", "Persone comuni come Renzo e Lucia", "Solo soldati francesi", "Solo i Bravi"],
      correct: 1,
      tema: "romanzo",
    },
    {
      q: "Qual è il «motore» del romanzo secondo le slide?",
      choices: ["Il denaro di Don Rodrigo", "La Provvidenza / Dio", "Il caso puro", "La polizia austriaca"],
      correct: 1,
      tema: "provvidenza",
    },
    {
      q: "Cosa fa l’Innominato dopo la conversione?",
      choices: ["Uccide Renzo", "Libera Lucia", "Fugge in Spagna", "Diventa parroco al posto di Don Abbondio"],
      correct: 1,
      tema: "personaggi",
    },
    {
      q: "Come muore Don Rodrigo?",
      choices: ["In duello", "Di peste", "Annegato nell’Adda", "Esiliato a Vienna"],
      correct: 1,
      tema: "provvidenza",
    },
    {
      q: "Manzoni rompe le unità aristoteliche. Quale affermazione è vera?",
      choices: ["Tutto avviene in un solo giorno e in un solo luogo", "Tempo lungo, luoghi molti, trama articolata", "Niente flashback e un solo personaggio", "Solo unità di luogo, niente altro"],
      correct: 1,
      tema: "romanzo",
    },
    {
      q: "Secondo Manzoni la letteratura deve essere…",
      choices: ["Solo per i dotti", "Comprensibile e utile (anche politica)", "Solo divertente", "Scritta solo in latino"],
      correct: 1,
      tema: "lingua",
    },
  ],
};
