window.TommasoData = {
  indizi: [
    {
      id: "i1",
      text: "Tutto ciò che si muove è mosso da altro → serve un Primo Motore immobile.",
      bin: "via-i",
      hint: "Parte dal movimento (cambiamento): Via I.",
    },
    {
      id: "i2",
      text: "Ogni effetto ha una causa → non si può risalire all’infinito → Causa Prima.",
      bin: "via-ii",
      hint: "Catena delle cause efficienti: Via II.",
    },
    {
      id: "i3",
      text: "Le cose possono esserci o non esserci → serve un Essere necessario.",
      bin: "via-iii",
      hint: "Contingenza vs necessità: Via III.",
    },
    {
      id: "i4",
      text: "Ci sono gradi di bontà e perfezione → c’è un Massimo, misura di ogni bene.",
      bin: "via-iv",
      hint: "Gradi di perfezione: Via IV.",
    },
    {
      id: "i5",
      text: "Anche gli esseri senza conoscenza agiscono per un fine → Ordinatore intelligente.",
      bin: "via-v",
      hint: "Finalità / teleologia: Via V.",
    },
    {
      id: "i6",
      text: "Una palla da biliardo si muove perché un’altra l’ha colpita: chi ha iniziato?",
      bin: "via-i",
      hint: "Esempio di movimento trasmesso: Via I.",
    },
    {
      id: "i7",
      text: "I genitori ti hanno generato, e così a ritroso: serve una causa non causata.",
      bin: "via-ii",
      hint: "Esempio di causa efficiente: Via II.",
    },
    {
      id: "i8",
      text: "Il mondo poteva non esserci: perché c’è qualcosa invece del nulla?",
      bin: "via-iii",
      hint: "Contingenza del mondo: Via III.",
    },
  ],
  bins: [
    { id: "via-i", label: "Via I · Motore" },
    { id: "via-ii", label: "Via II · Causa" },
    { id: "via-iii", label: "Via III · Necessario" },
    { id: "via-iv", label: "Via IV · Massimo" },
    { id: "via-v", label: "Via V · Fine" },
  ],
  cammino: [
    {
      id: "s1",
      luogo: "Chiostro",
      pin: "1",
      x: 12,
      y: 55,
      img: "img/tavole/01-incontro.jpg",
      tipo: "quiz",
      domanda: "Secondo Tommaso, fede e ragione…",
      opzioni: [
        { t: "Si contraddicono sempre: bisogna scegliere una sola", ok: false },
        { t: "Non si contraddicono: la ragione apre, la fede eleva", ok: true },
        { t: "La fede sostituisce del tutto la ragione", ok: false },
      ],
      spiegazione: "Per Tommaso verità di fede e verità di ragione hanno lo stesso Autore: non possono davvero contrastarsi.",
    },
    {
      id: "s2",
      luogo: "Via I",
      pin: "I",
      x: 28,
      y: 28,
      img: "img/tavole/02-prime-vie.jpg",
      tipo: "quiz",
      domanda: "La Via del moto conclude a…",
      opzioni: [
        { t: "Un Primo Motore immobile", ok: true },
        { t: "Un mondo eterno senza spiegazione", ok: false },
        { t: "Solo al caso cieco", ok: false },
      ],
      spiegazione: "Ciò che si muove è mosso da altro; non si può risalire all’infinito → Primo Motore.",
    },
    {
      id: "s3",
      luogo: "Via II",
      pin: "II",
      x: 48,
      y: 18,
      img: "img/tavole/02-prime-vie.jpg",
      tipo: "quiz",
      domanda: "La Via della causa efficiente porta a…",
      opzioni: [
        { t: "Una catena infinita di cause senza inizio", ok: false },
        { t: "Una Causa Prima non causata", ok: true },
        { t: "Solo alle leggi della fisica moderna", ok: false },
      ],
      spiegazione: "Ogni effetto ha causa; senza una Causa Prima la catena non spiegherebbe nulla.",
    },
    {
      id: "s4",
      luogo: "Via III",
      pin: "III",
      x: 68,
      y: 32,
      img: "img/tavole/03-altre-vie.jpg",
      tipo: "quiz",
      domanda: "La Via della contingenza distingue…",
      opzioni: [
        { t: "Esseri che possono non essere ed Essere necessario", ok: true },
        { t: "Solo buoni e cattivi", ok: false },
        { t: "Materie e antimaterie", ok: false },
      ],
      spiegazione: "Se tutto fosse contingente, a un certo punto non ci sarebbe nulla. Serve un Essere necessario.",
    },
    {
      id: "s5",
      luogo: "Via IV–V",
      pin: "IV",
      x: 82,
      y: 55,
      img: "img/tavole/03-altre-vie.jpg",
      tipo: "quiz",
      domanda: "Gradi di perfezione e finalità del mondo indicano…",
      opzioni: [
        { t: "Solo gusti soggettivi e illusioni", ok: false },
        { t: "Un Massimo Bene e un Ordinatore intelligente", ok: true },
        { t: "Che la natura non ha alcun ordine", ok: false },
      ],
      spiegazione: "Via IV: gradi → Massimo. Via V: cose senza conoscenza agiscono per un fine → Intelligenza ordinatrice.",
    },
    {
      id: "s6",
      luogo: "Legge naturale",
      pin: "LN",
      x: 55,
      y: 78,
      img: "img/tavole/04-legge-naturale.jpg",
      tipo: "morale",
      domanda: "Il primo precetto della legge naturale, per Tommaso, è…",
      opzioni: [
        { t: "Fare il bene e evitare il male", ok: true },
        { t: "Obbedire solo alla maggioranza", ok: false },
        { t: "Seguire sempre il piacere del momento", ok: false },
      ],
      spiegazione: "La legge naturale è partecipazione della creatura razionale alla legge eterna: il bene da fare, il male da evitare.",
    },
  ],
};
