window.Grammatica = {
  categorie: [
    {
      id: "avverbio",
      nome: "Avverbio",
      glifo: "▲",
      breve: "Modifica un verbo, un aggettivo o un altro avverbio.",
      colore: "#79c4ff",
      esempi: ["bene", "presto", "molto", "qui", "sempre", "forse"],
      trucco: "Risponde a «come?», «quando?», «dove?», «quanto?». Se lo togli, la frase resta in piedi.",
      sottotipi: [
        { nome: "di modo", breve: "Dice come avviene l’azione.", esempi: ["bene", "male", "volentieri", "lentamente", "così"] },
        { nome: "di tempo", breve: "Colloca l’azione nel tempo.", esempi: ["ora", "ieri", "presto", "sempre", "mai", "già"] },
        { nome: "di luogo", breve: "Colloca l’azione nello spazio.", esempi: ["qui", "là", "sopra", "lontano", "ovunque"] },
        { nome: "di quantità", breve: "Misura o gradua.", esempi: ["molto", "poco", "troppo", "abbastanza", "più"] },
        { nome: "di affermazione, negazione, dubbio", breve: "Esprime la posizione di chi parla.", esempi: ["sì", "no", "forse", "certamente", "neanche"] },
        { nome: "interrogativi ed esclamativi", breve: "Aprono una domanda o un’esclamazione.", esempi: ["come", "quando", "dove", "perché", "quanto"] },
      ],
    },
    {
      id: "preposizione",
      nome: "Preposizione",
      glifo: "●",
      breve: "Collega parole e introduce un complemento.",
      colore: "#4fd9c0",
      esempi: ["di", "a", "da", "in", "con", "su", "per", "tra", "del", "nel"],
      trucco: "Sta quasi sempre davanti a un nome o a un pronome, e da sola non significa nulla.",
      sottotipi: [
        { nome: "proprie (semplici)", breve: "Le nove di base.", esempi: ["di", "a", "da", "in", "con", "su", "per", "tra", "fra"] },
        { nome: "articolate", breve: "Preposizione fusa con l’articolo.", esempi: ["del", "allo", "dalla", "nei", "sugli", "col"] },
        { nome: "improprie", breve: "Parole nate come avverbi o aggettivi, usate da preposizione.", esempi: ["davanti", "dopo", "lungo", "secondo", "tranne", "durante"] },
        { nome: "locuzioni prepositive", breve: "Gruppi di parole con funzione di preposizione.", esempi: ["per mezzo di", "a causa di", "prima di", "invece di", "insieme con"] },
      ],
    },
    {
      id: "congiunzione",
      nome: "Congiunzione",
      glifo: "■",
      breve: "Unisce parole, frasi o proposizioni.",
      colore: "#ffc24d",
      esempi: ["e", "ma", "oppure", "perché", "se", "quando", "che", "benché"],
      trucco: "Sta in mezzo a due elementi e dice che rapporto logico c’è fra loro.",
      sottotipi: [
        { nome: "coordinanti copulative", breve: "Sommano due elementi.", esempi: ["e", "anche", "inoltre", "né"] },
        { nome: "coordinanti avversative", breve: "Oppongono due elementi.", esempi: ["ma", "però", "tuttavia", "anzi"] },
        { nome: "coordinanti disgiuntive", breve: "Mettono in alternativa.", esempi: ["o", "oppure", "ovvero"] },
        { nome: "coordinanti conclusive e dichiarative", breve: "Tirano una conseguenza o spiegano.", esempi: ["dunque", "quindi", "perciò", "cioè", "infatti"] },
        { nome: "subordinanti", breve: "Rendono una frase dipendente da un’altra.", esempi: ["perché", "poiché", "se", "benché", "affinché", "mentre", "che"] },
      ],
    },
    {
      id: "interiezione",
      nome: "Interiezione",
      glifo: "★",
      breve: "Esprime un’emozione o un richiamo improvviso.",
      colore: "#ff8fc4",
      esempi: ["ah", "oh", "ehi", "bravo", "aiuto", "uffa"],
      trucco: "È autonoma: la puoi isolare fra due virgole o farla seguire da un punto esclamativo.",
      sottotipi: [
        { nome: "proprie", breve: "Esistono solo come interiezione.", esempi: ["ah", "oh", "ehi", "ahimè", "uffa", "ohibò"] },
        { nome: "improprie", breve: "Altre parti del discorso usate come esclamazione.", esempi: ["bravo", "coraggio", "accidenti", "peccato", "aiuto"] },
        { nome: "locuzioni interiettive", breve: "Gruppi fissi di parole.", esempi: ["per carità", "santo cielo", "al diavolo"] },
        { nome: "onomatopee", breve: "Riproducono un suono.", esempi: ["bum", "patatrac", "zac", "eh"] },
      ],
    },
  ],

  fraseDemo: [
    { testo: "Ah", tipo: "interiezione" },
    { testo: ", ", tipo: null },
    { testo: "forse", tipo: "avverbio" },
    { testo: " arriverò ", tipo: null },
    { testo: "presto", tipo: "avverbio" },
    { testo: " ", tipo: null },
    { testo: "a", tipo: "preposizione" },
    { testo: " scuola, ", tipo: null },
    { testo: "ma", tipo: "congiunzione" },
    { testo: " ", tipo: null },
    { testo: "solo", tipo: "avverbio" },
    { testo: " ", tipo: null },
    { testo: "se", tipo: "congiunzione" },
    { testo: " finisco ", tipo: null },
    { testo: "in", tipo: "preposizione" },
    { testo: " tempo!", tipo: null },
  ],

  paroleLab: [
    { parola: "sempre", tipo: "avverbio", sotto: "di tempo" },
    { parola: "sotto", tipo: "preposizione", sotto: "impropria" },
    { parola: "perché", tipo: "congiunzione", sotto: "subordinante" },
    { parola: "ehi", tipo: "interiezione", sotto: "propria" },
    { parola: "molto", tipo: "avverbio", sotto: "di quantità" },
    { parola: "con", tipo: "preposizione", sotto: "propria" },
    { parola: "oppure", tipo: "congiunzione", sotto: "coordinante disgiuntiva" },
    { parola: "bravo", tipo: "interiezione", sotto: "impropria" },
    { parola: "qui", tipo: "avverbio", sotto: "di luogo" },
    { parola: "tra", tipo: "preposizione", sotto: "propria" },
    { parola: "quando", tipo: "congiunzione", sotto: "subordinante" },
    { parola: "oh", tipo: "interiezione", sotto: "propria" },
    { parola: "bene", tipo: "avverbio", sotto: "di modo" },
    { parola: "dal", tipo: "preposizione", sotto: "articolata" },
    { parola: "benché", tipo: "congiunzione", sotto: "subordinante" },
    { parola: "aiuto", tipo: "interiezione", sotto: "impropria" },
    { parola: "mai", tipo: "avverbio", sotto: "di tempo" },
    { parola: "su", tipo: "preposizione", sotto: "propria" },
    { parola: "che", tipo: "congiunzione", sotto: "subordinante" },
    { parola: "uffa", tipo: "interiezione", sotto: "propria" },
    { parola: "tuttavia", tipo: "congiunzione", sotto: "coordinante avversativa" },
    { parola: "davanti", tipo: "preposizione", sotto: "impropria" },
    { parola: "lentamente", tipo: "avverbio", sotto: "di modo" },
    { parola: "accidenti", tipo: "interiezione", sotto: "impropria" },
    { parola: "quindi", tipo: "congiunzione", sotto: "coordinante conclusiva" },
    { parola: "sugli", tipo: "preposizione", sotto: "articolata" },
    { parola: "abbastanza", tipo: "avverbio", sotto: "di quantità" },
    { parola: "patatrac", tipo: "interiezione", sotto: "onomatopea" },
  ],

  cloze: [
    {
      frase: ["Studio molto ", " voglio superare l’esame."],
      scelte: ["perché", "davanti", "uffa", "presto"],
      correct: 0,
      tipo: "congiunzione",
      spiega: "Introduce la causa e rende dipendente la seconda frase: congiunzione subordinante.",
    },
    {
      frase: ["Il manuale è ", " banco, accanto al tablet."],
      scelte: ["oppure", "sul", "ahimè", "spesso"],
      correct: 1,
      tipo: "preposizione",
      spiega: "«Sul» è preposizione articolata (su + il) e introduce un complemento di luogo.",
    },
    {
      frase: ["", "! Ho dimenticato la calcolatrice a casa."],
      scelte: ["Tra", "Anche", "Accidenti", "Molto"],
      correct: 2,
      tipo: "interiezione",
      spiega: "Esprime contrarietà improvvisa ed è isolata dal resto: interiezione impropria.",
    },
    {
      frase: ["La saldatura va eseguita ", ", senza fretta."],
      scelte: ["lentamente", "benché", "dalla", "ehi"],
      correct: 0,
      tipo: "avverbio",
      spiega: "Risponde a «come?» e modifica il verbo: avverbio di modo.",
    },
    {
      frase: ["Ho finito il disegno tecnico, ", " non l’ho ancora quotato."],
      scelte: ["perciò", "però", "cioè", "affinché"],
      correct: 1,
      tipo: "congiunzione",
      spiega: "Fra le due frasi c’è un’opposizione: congiunzione coordinante avversativa.",
    },
    {
      frase: ["Il tornio si è fermato ", " un guasto all’impianto elettrico."],
      scelte: ["a causa di", "insieme a", "oltre a", "invece di"],
      correct: 0,
      tipo: "preposizione",
      spiega: "«A causa di» è una locuzione prepositiva e introduce la causa.",
    },
    {
      frase: ["Non ho ", " capito il diagramma di flusso."],
      scelte: ["ancora", "dunque", "presso", "ohibò"],
      correct: 0,
      tipo: "avverbio",
      spiega: "Colloca l’azione nel tempo: avverbio di tempo.",
    },
    {
      frase: ["Ripassa la teoria ", " tu possa svolgere il laboratorio da solo."],
      scelte: ["mentre", "affinché", "tuttavia", "quasi"],
      correct: 1,
      tipo: "congiunzione",
      spiega: "Introduce il fine dell’azione: congiunzione subordinante finale.",
    },
  ],

  intrusi: [
    { parole: ["e", "ma", "oppure", "sopra"], intruso: 3, tipo: "preposizione", altri: "congiunzioni", spiega: "«Sopra» introduce un complemento: è preposizione impropria." },
    { parole: ["bene", "presto", "molto", "con"], intruso: 3, tipo: "preposizione", altri: "avverbi", spiega: "«Con» collega e introduce un complemento: preposizione propria." },
    { parole: ["ah", "oh", "ehi", "già"], intruso: 3, tipo: "avverbio", altri: "interiezioni", spiega: "«Già» indica il tempo dell’azione: è un avverbio." },
    { parole: ["del", "nella", "sugli", "dunque"], intruso: 3, tipo: "congiunzione", altri: "preposizioni articolate", spiega: "«Dunque» tira una conseguenza: congiunzione coordinante conclusiva." },
    { parole: ["poiché", "benché", "affinché", "purtroppo"], intruso: 3, tipo: "avverbio", altri: "congiunzioni subordinanti", spiega: "«Purtroppo» esprime la valutazione di chi parla: è un avverbio." },
    { parole: ["accidenti", "coraggio", "peccato", "invece"], intruso: 3, tipo: "avverbio", altri: "interiezioni improprie", spiega: "«Invece» mette in contrapposizione: non è un’esclamazione." },
  ],

  frasiAnalisi: [
    [
      { testo: "Purtroppo", tipo: "avverbio" },
      { testo: " il collaudo è fallito, ", tipo: null },
      { testo: "ma", tipo: "congiunzione" },
      { testo: " ripeteremo la prova ", tipo: null },
      { testo: "domani", tipo: "avverbio" },
      { testo: ".", tipo: null },
    ],
    [
      { testo: "Ehi", tipo: "interiezione" },
      { testo: ", metti i guanti ", tipo: null },
      { testo: "prima", tipo: "avverbio" },
      { testo: " ", tipo: null },
      { testo: "di", tipo: "preposizione" },
      { testo: " toccare la piastra!", tipo: null },
    ],
    [
      { testo: "Il programma gira ", tipo: null },
      { testo: "bene", tipo: "avverbio" },
      { testo: " ", tipo: null },
      { testo: "sul", tipo: "preposizione" },
      { testo: " server, ", tipo: null },
      { testo: "quindi", tipo: "congiunzione" },
      { testo: " l’errore è ", tipo: null },
      { testo: "certamente", tipo: "avverbio" },
      { testo: " ", tipo: null },
      { testo: "nel", tipo: "preposizione" },
      { testo: " client.", tipo: null },
    ],
  ],

  proveGioco: [
    { q: "Quale di queste parole è un avverbio?", options: ["libro", "velocemente", "bello", "correre"], correct: 1, tag: "avverbio", explain: "«Velocemente» modifica il verbo e indica il modo: avverbio di modo." },
    { q: "«Di», «a», «da», «in» sono…", options: ["congiunzioni", "preposizioni proprie", "interiezioni", "avverbi"], correct: 1, tag: "preposizione", explain: "Sono le preposizioni proprie: collegano parole e introducono complementi." },
    { q: "In «Studio perché voglio imparare», «perché» è…", options: ["un avverbio", "una preposizione", "una congiunzione subordinante", "un’interiezione"], correct: 2, tag: "congiunzione", explain: "Unisce due proposizioni rendendone una dipendente e ne esprime la causa." },
    { q: "«Ah, che sorpresa!» — «Ah» è…", options: ["un avverbio", "una preposizione", "una congiunzione", "un’interiezione propria"], correct: 3, tag: "interiezione", explain: "Esiste solo come esclamazione: interiezione propria." },
    { q: "Le parti invariabili del discorso…", options: ["cambiano genere e numero", "non si flettono", "sono solo i verbi", "esistono solo al plurale"], correct: 1, tag: "teoria", explain: "«Invariabili» significa che non hanno flessione di genere, numero o persona." },
    { q: "«Nel», «del», «sul» sono…", options: ["avverbi", "preposizioni articolate", "interiezioni", "congiunzioni"], correct: 1, tag: "preposizione", explain: "Nascono dalla fusione di preposizione e articolo." },
    { q: "«E», «ma», «oppure» sono congiunzioni…", options: ["coordinanti", "solo subordinanti", "prepositive", "avverbiali"], correct: 0, tag: "congiunzione", explain: "Collegano elementi dello stesso livello: sono coordinanti." },
    { q: "In «Corro spesso al parco», «spesso» è…", options: ["una preposizione", "un avverbio di frequenza", "una congiunzione", "un’interiezione"], correct: 1, tag: "avverbio", explain: "Dice quante volte avviene l’azione: avverbio di tempo." },
    { q: "Quale gruppo è una locuzione prepositiva?", options: ["a causa di", "tuttavia", "santo cielo", "abbastanza"], correct: 0, tag: "preposizione", explain: "Più parole che insieme funzionano da preposizione e introducono la causa." },
    { q: "In «Benché piova, esco», «benché» introduce…", options: ["una causa", "una concessione", "un fine", "una conseguenza"], correct: 1, tag: "congiunzione", explain: "È una subordinante concessiva: ammette un ostacolo che non ferma l’azione." },
    { q: "«Bravo!» gridato a fine spettacolo è…", options: ["un aggettivo, sempre", "un’interiezione impropria", "un avverbio", "una congiunzione"], correct: 1, tag: "interiezione", explain: "È un aggettivo usato come esclamazione: interiezione impropria." },
    { q: "Quale parola NON è invariabile?", options: ["velocemente", "rapido", "dunque", "presso"], correct: 1, tag: "teoria", explain: "«Rapido» fa rapida, rapidi, rapide: è un aggettivo. Gli altri non cambiano mai." },
    { q: "In «Cammina lungo il fiume», «lungo» è…", options: ["un aggettivo", "una preposizione impropria", "un avverbio di luogo", "una congiunzione"], correct: 1, tag: "preposizione", explain: "Qui regge un nome e introduce un complemento: preposizione impropria." },
    { q: "«Cioè» e «infatti» sono congiunzioni…", options: ["disgiuntive", "dichiarative", "concessive", "temporali"], correct: 1, tag: "congiunzione", explain: "Chiariscono o confermano quanto appena detto: coordinanti dichiarative." },
    { q: "Quale avverbio esprime dubbio?", options: ["certamente", "forse", "neanche", "sempre"], correct: 1, tag: "avverbio", explain: "«Forse» lascia la cosa incerta: avverbio di dubbio." },
    { q: "In «Non ci vado né oggi né domani», «né» è…", options: ["un avverbio di negazione", "una congiunzione copulativa", "una preposizione", "un’interiezione"], correct: 1, tag: "congiunzione", explain: "Somma due elementi in forma negativa: congiunzione copulativa." },
    { q: "«Patatrac» è…", options: ["un’onomatopea", "un avverbio di modo", "una preposizione impropria", "una congiunzione"], correct: 0, tag: "interiezione", explain: "Riproduce un rumore: onomatopea, sottotipo di interiezione." },
    { q: "Quante sono le parti invariabili del discorso?", options: ["2", "4", "6", "9"], correct: 1, tag: "teoria", explain: "Quattro: avverbio, preposizione, congiunzione, interiezione." },
  ],

  nomeCategoria(id) {
    return this.categorie.find((c) => c.id === id)?.nome || id;
  },

  categoria(id) {
    return this.categorie.find((c) => c.id === id);
  },
};
