window.Grammatica = {
  categorie: [
    {
      id: "avverbio",
      nome: "Avverbio",
      breve: "Modifica un verbo, un aggettivo o un altro avverbio.",
      colore: "#7ec8ff",
      esempi: ["bene", "presto", "molto", "qui", "sempre", "forse"],
      trucco: "Spesso risponde a «come?», «quando?», «dove?», «quanto?».",
    },
    {
      id: "preposizione",
      nome: "Preposizione",
      breve: "Collega parole e introduce un complemento.",
      colore: "#5ee0c5",
      esempi: ["di", "a", "da", "in", "con", "su", "per", "tra", "del", "nel"],
      trucco: "Di solito sta prima di un nome o di un pronome.",
    },
    {
      id: "congiunzione",
      nome: "Congiunzione",
      breve: "Unisce parole, frasi o proposizioni.",
      colore: "#ffc857",
      esempi: ["e", "ma", "oppure", "perché", "se", "quando", "che", "benché"],
      trucco: "Introduce un legame logico tra due parti del discorso.",
    },
    {
      id: "interiezione",
      nome: "Interiezione",
      breve: "Esprime un’emozione o un richiamo improvviso.",
      colore: "#ff8b8b",
      esempi: ["ah", "oh", "ehi", "bravo", "aiuto", "uffa"],
      trucco: "Spesso è isolata e seguita da un punto esclamativo.",
    },
  ],

  fraseDemo: [
    { testo: "Ah", tipo: "interiezione" },
    { testo: ",", tipo: null },
    { testo: " ", tipo: null },
    { testo: "forse", tipo: "avverbio" },
    { testo: " ", tipo: null },
    { testo: "arriverò", tipo: null },
    { testo: " ", tipo: null },
    { testo: "presto", tipo: "avverbio" },
    { testo: " ", tipo: null },
    { testo: "a", tipo: "preposizione" },
    { testo: " ", tipo: null },
    { testo: "scuola", tipo: null },
    { testo: ",", tipo: null },
    { testo: " ", tipo: null },
    { testo: "ma", tipo: "congiunzione" },
    { testo: " ", tipo: null },
    { testo: "solo", tipo: "avverbio" },
    { testo: " ", tipo: null },
    { testo: "se", tipo: "congiunzione" },
    { testo: " ", tipo: null },
    { testo: "finisco", tipo: null },
    { testo: " ", tipo: null },
    { testo: "in", tipo: "preposizione" },
    { testo: " ", tipo: null },
    { testo: "tempo", tipo: null },
    { testo: "!", tipo: null },
  ],

  paroleLab: [
    { parola: "sempre", tipo: "avverbio" },
    { parola: "sotto", tipo: "preposizione" },
    { parola: "perché", tipo: "congiunzione" },
    { parola: "ehi", tipo: "interiezione" },
    { parola: "molto", tipo: "avverbio" },
    { parola: "con", tipo: "preposizione" },
    { parola: "oppure", tipo: "congiunzione" },
    { parola: "bravo", tipo: "interiezione" },
    { parola: "qui", tipo: "avverbio" },
    { parola: "tra", tipo: "preposizione" },
    { parola: "quando", tipo: "congiunzione" },
    { parola: "oh", tipo: "interiezione" },
    { parola: "bene", tipo: "avverbio" },
    { parola: "dal", tipo: "preposizione" },
    { parola: "benché", tipo: "congiunzione" },
    { parola: "aiuto", tipo: "interiezione" },
    { parola: "mai", tipo: "avverbio" },
    { parola: "su", tipo: "preposizione" },
    { parola: "che", tipo: "congiunzione" },
    { parola: "uffa", tipo: "interiezione" },
  ],

  proveGioco: [
    {
      q: "Quale di queste parole è un avverbio?",
      options: ["libro", "velocemente", "bello", "correre"],
      correct: 1,
      explain: "«Velocemente» modifica il verbo e indica il modo: è un avverbio di modo.",
    },
    {
      q: "«Di», «a», «da», «in» sono…",
      options: ["congiunzioni", "preposizioni", "interiezioni", "avverbi"],
      correct: 1,
      explain: "Sono preposizioni semplici: collegano parole e introducono complementi.",
    },
    {
      q: "Nella frase «Studio perché voglio imparare», «perché» è…",
      options: ["un avverbio", "una preposizione", "una congiunzione", "un’interiezione"],
      correct: 2,
      explain: "Unisce due proposizioni e spiega la causa: è una congiunzione.",
    },
    {
      q: "«Ah, che sorpresa!» — «Ah» è…",
      options: ["un avverbio", "una preposizione", "una congiunzione", "un’interiezione"],
      correct: 3,
      explain: "Esprime stupore in modo improvviso: è un’interiezione.",
    },
    {
      q: "Le parti invariabili del discorso…",
      options: [
        "cambiano genere e numero",
        "non si flettono",
        "sono solo i verbi",
        "esistono solo al plurale",
      ],
      correct: 1,
      explain: "Sono dette «invariabili» perché non hanno flessioni di genere, numero o persona.",
    },
    {
      q: "Quale parola è una preposizione?",
      options: ["forse", "sopra", "e", "oh"],
      correct: 1,
      explain: "«Sopra» introduce un complemento di luogo: è una preposizione.",
    },
    {
      q: "«E», «ma», «oppure» sono congiunzioni…",
      options: ["coordinanti", "solo subordinanti", "prepositive", "avverbiali"],
      correct: 0,
      explain: "Collegano elementi dello stesso livello: sono congiunzioni coordinanti.",
    },
    {
      q: "Quale domanda aiuta a riconoscere un avverbio?",
      options: ["Chi? Che cosa?", "Come? Quando? Dove?", "Di chi? A chi?", "Ah! Oh!"],
      correct: 1,
      explain: "Gli avverbi rispondono spesso a domande come «come?», «quando?», «dove?», «quanto?».",
    },
    {
      q: "«Nel», «del», «sul» sono…",
      options: ["avverbi", "preposizioni articolate", "interiezioni", "congiunzioni"],
      correct: 1,
      explain: "Uniscono una preposizione e un articolo: sono preposizioni articolate.",
    },
    {
      q: "Quale di queste è un’interiezione?",
      options: ["dopo", "benché", "ehi", "lentamente"],
      correct: 2,
      explain: "«Ehi» serve per richiamare qualcuno: è un’interiezione.",
    },
    {
      q: "Nella frase «Corro spesso al parco», «spesso» è…",
      options: ["una preposizione", "un avverbio di frequenza", "una congiunzione", "un’interiezione"],
      correct: 1,
      explain: "Indica quante volte avviene l’azione: è un avverbio di frequenza.",
    },
    {
      q: "Quante sono le parti invariabili del discorso?",
      options: ["2", "4", "6", "9"],
      correct: 1,
      explain: "Sono quattro: avverbi, preposizioni, congiunzioni e interiezioni.",
    },
  ],

  nomeCategoria(id) {
    return this.categorie.find((c) => c.id === id)?.nome || id;
  },
};
