window.KierkegaardData = {
  stadi: [
    {
      id: "s1",
      text: "Vivo di serate, divertimenti e novità: domani si vedrà",
      bin: "estetico",
      hint: "Priorità al piacere e all’attimo: tipico dello stadio estetico.",
    },
    {
      id: "s2",
      text: "Scelgo un impegno (studio, lavoro, relazione) e ne rispondo",
      bin: "etico",
      hint: "Scelta e responsabilità: cuore dello stadio etico.",
    },
    {
      id: "s3",
      text: "Affido il senso ultimo a qualcosa che supera il calcolo",
      bin: "religioso",
      hint: "Oltre etica e piacere: relazione assoluta (stadio religioso / salto).",
    },
    {
      id: "s4",
      text: "Cambio hobby ogni settimana per non annoiarmi",
      bin: "estetico",
      hint: "Fuga dalla noia con nuovi stimoli = estetico.",
    },
    {
      id: "s5",
      text: "Mantengo una promessa anche quando non mi conviene",
      bin: "etico",
      hint: "La massima etica vale oltre l’umore del momento.",
    },
    {
      id: "s6",
      text: "Accetto un rischio di fede che la sola ragione non «dimostra»",
      bin: "religioso",
      hint: "Il salto non è dimostrazione scientifica: è decisione esistenziale.",
    },
  ],
  bins: [
    { id: "estetico", label: "Estetico" },
    { id: "etico", label: "Etico" },
    { id: "religioso", label: "Religioso" },
  ],
  autaut: [
    {
      id: "f1",
      luogo: "Molo",
      pin: "1",
      x: 12,
      y: 78,
      tipo: "quiz",
      domanda: "Kierkegaard è soprattutto…",
      opzioni: [
        { t: "Un filosofo dell’esistenza e della scelta individuale", ok: true },
        { t: "Un fisico che studia i fenomeni", ok: false },
        { t: "Un poeta solo romantico, senza tesi", ok: false },
      ],
      spiegazione: "Parte dalla vita concreta del singolo: angoscia, scelta, fede — non da un sistema astratto «chiuso».",
    },
    {
      id: "f2",
      luogo: "Caffè",
      pin: "2",
      x: 28,
      y: 52,
      tipo: "quiz",
      domanda: "Nello stadio estetico predominano…",
      opzioni: [
        { t: "Il dovere e le promesse", ok: false },
        { t: "Piacere, varietà, istante (poi spesso la noia)", ok: true },
        { t: "Il salto della fede", ok: false },
      ],
      spiegazione: "L’estetico cerca il interessante; quando lo stimolo cala, compare la noia.",
    },
    {
      id: "f3",
      luogo: "Bivio",
      pin: "3",
      x: 48,
      y: 68,
      tipo: "scelta",
      domanda: "«Aut-aut» (o… o) invita soprattutto a…",
      opzioni: [
        { t: "Rinviare sempre: «si vedrà»", ok: false },
        { t: "Prendere una decisione vera, non restare a metà", ok: true },
        { t: "Seguire solo la maggioranza", ok: false },
      ],
      spiegazione: "Per Kierkegaard restare eternamente «indecisi» è già una (cattiva) scelta: evita di diventare se stessi.",
    },
    {
      id: "f4",
      luogo: "Nebbia",
      pin: "4",
      x: 62,
      y: 38,
      tipo: "quiz",
      domanda: "L’angoscia, in Kierkegaard, nasce soprattutto da…",
      opzioni: [
        { t: "Un pericolo esterno già definito", ok: false },
        { t: "La libertà: posso scegliere in più direzioni", ok: true },
        { t: "La mancanza totale di opzioni", ok: false },
      ],
      spiegazione: "Non è solo paura di un oggetto: è vertigine davanti al possibile.",
    },
    {
      id: "f5",
      luogo: "Chiesa",
      pin: "5",
      x: 78,
      y: 58,
      tipo: "scelta",
      domanda: "Il «salto della fede» significa…",
      opzioni: [
        { t: "Una dimostrazione scientifica di Dio", ok: false },
        { t: "Una decisione che va oltre la sola ragione dimostrativa", ok: true },
        { t: "Ignorare del tutto l’etica", ok: false },
      ],
      spiegazione: "Non sostituisce la vita etica con il capriccio: apre a una relazione assoluta non riducibile al calcolo.",
    },
    {
      id: "f6",
      luogo: "Piazza",
      pin: "6",
      x: 90,
      y: 28,
      tipo: "quiz",
      domanda: "Dopo Kierkegaard, Sartre sottolinea soprattutto…",
      opzioni: [
        { t: "Che l’essenza umana è già data dalla natura", ok: false },
        { t: "Che l’esistenza precede l’essenza: ti fai con le scelte", ok: true },
        { t: "Che non esiste libertà", ok: false },
      ],
      spiegazione: "Esistenzialismo «ateo»: senza essenza prestabilita, la responsabilità delle scelte cresce.",
    },
  ],
};
