window.LogicaData = {
  casi: [
    {
      id: "c1",
      text: "Tutti gli uomini sono mortali; Socrate è un uomo; quindi Socrate è mortale",
      bin: "deduttivo",
      hint: "Dalle premesse generali scende una conclusione necessaria: metodo deduttivo.",
    },
    {
      id: "c2",
      text: "Ho visto tanti cigni bianchi: quindi tutti i cigni sono bianchi",
      bin: "induttivo",
      hint: "Da molti casi particolari generalizzi: tipico dell’induzione (probabile, non certa).",
    },
    {
      id: "c3",
      text: "L’acqua bolle a 100 °C a livello del mare; questa è acqua pura a livello del mare; quindi bolle a 100 °C",
      bin: "deduttivo",
      hint: "Premessa generale + caso → conclusione che segue per necessità.",
    },
    {
      id: "c4",
      text: "Il farmaco ha funzionato su 800 pazienti su 1000: probabilmente funziona anche sul prossimo",
      bin: "induttivo",
      hint: "Dai dati clinici sali a una previsione: induzione (probabilità, non certezza assoluta).",
    },
    {
      id: "c5",
      text: "Se un triangolo ha tre lati uguali, gli angoli sono uguali; ABC è equilatero; quindi i suoi angoli sono uguali",
      bin: "deduttivo",
      hint: "Schema da teorema: dalle premesse la conclusione è obbligata.",
    },
    {
      id: "c6",
      text: "In classe i compagni misurati sono tutti sopra 1,60 m: quindi tutta la scuola è alta così",
      bin: "induttivo",
      hint: "Generalizzi da un campione: induzione (e qui il salto è rischioso).",
    },
  ],
  bins: [
    { id: "deduttivo", label: "Deduttivo" },
    { id: "induttivo", label: "Induttivo" },
  ],
  percorso: [
    {
      id: "p1",
      luogo: "Bivio",
      pin: "1",
      x: 12,
      y: 70,
      tipo: "quiz",
      domanda: "Il metodo deduttivo va soprattutto…",
      opzioni: [
        { t: "Dal generale al particolare", ok: true },
        { t: "Dal particolare al generale", ok: false },
        { t: "Solo per indovinare senza premesse", ok: false },
      ],
      spiegazione: "Nella deduzione parti da regole/premesse generali e scendi al caso concreto.",
    },
    {
      id: "p2",
      luogo: "Cigni",
      pin: "2",
      x: 28,
      y: 45,
      tipo: "quiz",
      domanda: "«Ho visto solo cigni bianchi → tutti i cigni sono bianchi» è…",
      opzioni: [
        { t: "Deduzione necessaria", ok: false },
        { t: "Induzione (generalizzazione)", ok: true },
        { t: "Né l’uno né l’altro", ok: false },
      ],
      spiegazione: "Dai casi osservati sali a una regola generale: è induttivo e resta aperto a controesempi.",
    },
    {
      id: "p3",
      luogo: "Premesse",
      pin: "3",
      x: 45,
      y: 62,
      tipo: "quiz",
      domanda: "Se le premesse di un ragionamento deduttivo valido sono vere…",
      opzioni: [
        { t: "La conclusione è vera", ok: true },
        { t: "La conclusione è solo probabile", ok: false },
        { t: "Non conta: la deduzione è sempre falsa", ok: false },
      ],
      spiegazione: "Validità + premesse vere → conclusione certa. Citazione-guida del percorso.",
    },
    {
      id: "p4",
      luogo: "Laboratorio",
      pin: "4",
      x: 60,
      y: 38,
      tipo: "quiz",
      domanda: "La scienza sperimentale (prove, dati, prove ripetute) usa soprattutto…",
      opzioni: [
        { t: "Solo deduzione pura, senza osservazioni", ok: false },
        { t: "Induzione (e poi spesso controlla/deduce conseguenze)", ok: true },
        { t: "Né metodo né ipotesi", ok: false },
      ],
      spiegazione: "Dai fatti sali a ipotesi (induzione); poi ne ricavi conseguenze da verificare.",
    },
    {
      id: "p5",
      luogo: "Clinica",
      pin: "5",
      x: 75,
      y: 55,
      tipo: "quiz",
      domanda: "Un farmaco ha funzionato su molti pazienti: sul prossimo…",
      opzioni: [
        { t: "È certo al 100% come un teorema", ok: false },
        { t: "È probabile, non assolutamente certo", ok: true },
        { t: "Non c’entra con la logica", ok: false },
      ],
      spiegazione: "L’induzione medica dà probabilità utile, non la certezza della deduzione formale.",
    },
    {
      id: "p6",
      luogo: "Chalkboard",
      pin: "6",
      x: 90,
      y: 30,
      tipo: "quiz",
      domanda: "Quale contrasto è corretto?",
      opzioni: [
        { t: "Deduttivo → certezza (se valido); induttivo → probabilità", ok: true },
        { t: "Induttivo → sempre certezza assoluta", ok: false },
        { t: "Deduttivo → solo opinioni senza premesse", ok: false },
      ],
      spiegazione: "Ricorda: direzione diversa (generale↔particolare) e forza diversa (necessità vs probabilità).",
    },
  ],
};
